# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlanningApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlanningApp
pod 'FSCalendar'
pod 'RealmSwift'
pod 'Firebase/Analytics'
pod 'GoogleSignIn'
pod 'Firebase/Database'
pod 'Firebase/Auth'

end
